require("config.globals")
require("config.options")
require("config.keymaps")
require("config.plugins.plenary")
require("config.plugins.mini")
require("config.plugins.oil")
require("config.plugins.colorschemes")
require("config.plugins.conform")
require("config.plugins.which-key")
require("config.plugins.telescope-ui-select")
require("config.plugins.telescope-fzf-native")
require("config.plugins.telescope")
require("config.plugins.treepairs")
require("config.plugins.treesitter")
require("config.plugins.flash")
require("config.plugins.lazydev")
require("config.plugins.lsp")
require("config.plugins.completion")

-- New UI opt-in
require("vim._core.ui2").enable({})
