# .zshrc is executed when the shell starts

# This writes out the current zsh version to the screen
zsh --version
# This reminds me that this script is run
echo "executing .zshrc"

# Alias commands
alias l='eza'             # eza is ls replacement
alias la='eza -a'         # hidden files
alias ll='eza -l'         # long listing
alias lo='eza -1'         # single column
alias lal='eza -la'       # long listing
alias g='zoxide'
alias mkdir='mkdir -pv'   #-p create intermediate dirs
alias v='nvim'
alias cp='cp -iv'         #-i prompt to overwrite
alias mv='mv -iv'         #-i prompt to overwrite
alias c='clear'
alias p='pwd'
alias path='echo $PATH | tr ":" "\n"'
alias tt='~/repos/dotfiles/tmux/tmux-sessionizer'
alias reload='source ~/.zshrc'        #reload bach profile in current session
alias gs='git status'
alias gc='git cat-file -p '
alias gl='git log --oneline --graph --parents -10'
alias root='cd $(git rev-parse --show-toplevel)'

# Update path
export PATH=~/bin:/opt/homebrew/opt/postgresql@16/bin:/opt/homebrew/sbin:/opt/homebrew/bin:~/go/bin:$PATH

# Set the command line mode
# Emacs is the default, but this reminds me that it is set
set -o emacs

# Set the system editor. This is used by a variety or system tools.
export EDITOR=nvim
export VISUAL="$EDITOR"

# Git display options
# This will handle branch displays etc. inline rather than opening a file
export LESS=-FRX

# Load asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh
export ASDF_GOLANG_MOD_VERSION_ENABLED=true

# Prompt configuration
# https://github.com/spaceship-prompt/spaceship-prompt
# https://spaceship-prompt.sh/
# config in ~/.config/spaceship.zsh
# extension that displays command line vi mode
# source ~/repos/spaceship-vi-mode/spaceship-vi-mode.plugin.zsh
source $(brew --prefix)/opt/spaceship/spaceship.zsh

# AUTOCOMPLETION
# Add all the extensions provided by Homebrew packages
# I export fpath so I have access to the fpath value later if investigation is 
# required.
export fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
# Add extensions from the zsh-completions package
# https://github.com/zsh-users/zsh-completions
# this adds a ton of useful stuff, esp. Rails for me.
# export fpath=(~/repos/zsh-completions/src $fpath)
# This enables expansion in the middle of a line rather than only at the end.
# Useful when using the prefix of a previous command without deleting to the
# end of the line.
bindkey "TAB" expand-or-complete-prefix
# initialize autocompletion
autoload -U compinit && compinit

# history setup
HISTSIZE=5000
HISTFILE=$HOME/.zhistory
SAVEHIST=5000
HISTDUP=erase
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS


# autocompletion using arrow keys (based on history)
# bindkey '\e[A' history-search-backward
bindkey '\e[A' history-substring-search-up
# bindkey '\e[B' history-search-forward
bindkey '\e[B' history-substring-search-down

# brew install zsh-history-substring-search
# https://github.com/zsh-users/zsh-history-substring-search.git
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# brew install zsh-syntax-highlighting
# https://github.com/zsh-users/zsh-syntax-highlighting.git
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# brew install zsh-autosuggestions
# https://github.com/zsh-users/zsh-autosuggestions.git
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Load settings specific to this setup (if required).
if [ -f ~/.zshrc.after ]; then . ~/.zshrc.after; fi

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
